import 'bloc/queue_tab_container_bloc.dart';import 'models/queue_tab_container_model.dart';import 'package:basri_s_application28/core/app_export.dart';import 'package:basri_s_application28/presentation/downloaded_page/downloaded_page.dart';import 'package:basri_s_application28/presentation/queue_page/queue_page.dart';import 'package:basri_s_application28/presentation/your_likes_page/your_likes_page.dart';import 'package:basri_s_application28/widgets/app_bar/appbar_image.dart';import 'package:basri_s_application28/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application28/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class QueueTabContainerScreen extends StatefulWidget {@override _QueueTabContainerScreenState createState() =>  _QueueTabContainerScreenState();
static Widget builder(BuildContext context) { return BlocProvider<QueueTabContainerBloc>(create: (context) => QueueTabContainerBloc(QueueTabContainerState(queueTabContainerModelObj: QueueTabContainerModel()))..add(QueueTabContainerInitialEvent()), child: QueueTabContainerScreen()); } 
onTapArrowleft27(BuildContext context) { NavigatorService.goBack(); } 
 }

// ignore_for_file: must_be_immutable
class _QueueTabContainerScreenState extends State<QueueTabContainerScreen> with  TickerProviderStateMixin {late TabController group244Controller;

@override void initState() { super.initState(); group244Controller = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { return BlocBuilder<QueueTabContainerBloc, QueueTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(38), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24), onTap: () {onTapArrowleft27(context);}), title: AppbarTitle(text: "lbl_podcasts".tr, margin: getMargin(left: 16)), actions: [AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgSearch, margin: getMargin(left: 24)), AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgClock28x28, margin: getMargin(left: 20, right: 24))]), body: SizedBox(width: size.width, child: SingleChildScrollView(child: Padding(padding: getPadding(top: 42), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(39), width: double.maxFinite, child: TabBar(controller: group244Controller, labelColor: ColorConstant.redA70002, labelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), unselectedLabelColor: ColorConstant.gray500, unselectedLabelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), indicatorColor: ColorConstant.redA70002, tabs: [Tab(child: Text("lbl_your_likes".tr, overflow: TextOverflow.ellipsis)), Tab(child: Text("lbl_queue".tr, overflow: TextOverflow.ellipsis)), Tab(child: Text("lbl_downloaded".tr, overflow: TextOverflow.ellipsis))])), Container(height: getVerticalSize(797), child: TabBarView(controller: group244Controller, children: [YourLikesPage.builder(context), QueuePage.builder(context), DownloadedPage.builder(context)]))]))))));}); } 
onTapArrowleft27(BuildContext context) { NavigatorService.goBack(); } 
 }
