import 'bloc/followers_details_tab_container_bloc.dart';import 'models/followers_details_tab_container_model.dart';import 'package:basri_s_application28/core/app_export.dart';import 'package:basri_s_application28/presentation/followers_details_page/followers_details_page.dart';import 'package:basri_s_application28/widgets/app_bar/appbar_image.dart';import 'package:basri_s_application28/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class FollowersDetailsTabContainerScreen extends StatefulWidget {@override _FollowersDetailsTabContainerScreenState createState() =>  _FollowersDetailsTabContainerScreenState();
static Widget builder(BuildContext context) { return BlocProvider<FollowersDetailsTabContainerBloc>(create: (context) => FollowersDetailsTabContainerBloc(FollowersDetailsTabContainerState(followersDetailsTabContainerModelObj: FollowersDetailsTabContainerModel()))..add(FollowersDetailsTabContainerInitialEvent()), child: FollowersDetailsTabContainerScreen()); } 
onTapArrowleft22(BuildContext context) { NavigatorService.goBack(); } 
 }

// ignore_for_file: must_be_immutable
class _FollowersDetailsTabContainerScreenState extends State<FollowersDetailsTabContainerScreen> with  TickerProviderStateMixin {late TabController group44Controller;

@override void initState() { super.initState(); group44Controller = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { return BlocBuilder<FollowersDetailsTabContainerBloc, FollowersDetailsTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(50), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24, top: 11, bottom: 11), onTap: () {onTapArrowleft22(context);}), actions: [AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgSearch, margin: getMargin(left: 24, top: 11, right: 11)), AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgClock28x28, margin: getMargin(left: 20, top: 11, right: 35))]), body: Container(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(39), width: double.maxFinite, margin: getMargin(top: 25), child: TabBar(controller: group44Controller, labelColor: ColorConstant.redA70002, labelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), unselectedLabelColor: ColorConstant.gray500, unselectedLabelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), indicatorColor: ColorConstant.redA70002, tabs: [Tab(child: Text("lbl_followers".tr, overflow: TextOverflow.ellipsis)), Tab(child: Text("lbl_following".tr, overflow: TextOverflow.ellipsis))])), Container(height: getVerticalSize(767), child: TabBarView(controller: group44Controller, children: [FollowersDetailsPage.builder(context), FollowersDetailsPage.builder(context)]))]))));}); } 
onTapArrowleft22(BuildContext context) { NavigatorService.goBack(); } 
 }
